### ISSUE TITLE
I want to merge two models into one, but keep reporting the error "attempt to clone with unknown class" 

### ISSUE THREAD

**Issue by wwr1982** [iTwin/itwinjs-core#6332] opened 2024-01-01 01:27 UTC
**My code is as follows:**

```ts
Logger.initializeToConsole();
Logger.setLevelDefault(LogLevel.Trace);
Logger.setLevel("imodel-transformer", LogLevel.Trace);
let sourceDb: IModelDb;
let sourceDb2: IModelDb;
let targetDb: IModelDb;
const sourceFile ="C:\Users\wwr\Downloads\aa\aa.bim";
const sourceFile2 ="C:\Users\wwr\Downloads\bb\bb.bim";
const targetFile ="C:\Users\wwr\Downloads\c\c.bim";
sourceDb = SnapshotDb.openFile(sourceFile);
sourceDb2 = SnapshotDb.openFile(sourceFile2);
if (IModelJsFs.existsSync(targetFile)) {
  IModelJsFs.removeSync(targetFile);
}
targetDb = StandaloneDb.createEmpty(targetFile, { // use StandaloneDb instead of SnapshotDb to enable processChanges testing
  rootSubject: { name: ${sourceDb.rootSubject.name}-Transformed },
  ecefLocation: sourceDb.ecefLocation,
});
const transformerOptions: TransformerOptions = {
  simplifyElementGeometry:true,
  noProvenance:true,
};
try{
  await Transformer.transformAll(sourceDb, targetDb, transformerOptions);
  await Transformer.transformAll(sourceDb2, targetDb, transformerOptions);
  sourceDb.close();
  targetDb.close();
  return "test";
}
catch(error:any)
{
  console.log(${error.message}\n${error.stack});
}
return "OK";
```

**My files to be merged are：**
[bimfile.zip](https://github.com/iTwin/itwinjs-core/files/13802492/bimfile.zip)

Thank you！

**Comment by ben-polinsky** [comment] 2024-01-02 14:17
@MichaelBelousov

**Comment by MichaelBelousov** [comment] 2024-01-02 14:54
@wwr1982 `Transformer.transformAll` is from the test-app, which is a testing tool. I recommend using the transformer library directly unless you are trying to hack the test-app for a basic CLI.

So you should be using `IModelTransformer.processAll` (the library equivalent of `transformAll`), but before that you must use `IModelTransformer.processSchemas`, which is required unless you are 100% sure your iModels will never have differing schema versions.

**Comment by MichaelBelousov** [comment] 2024-01-02 15:13
also next time please include a complete reproduction so it's less work on the maintainers to piece together your code into something that we can (safely) run and will accurately depict your issue.

<details>
<summary>My version</summary>
<pre>
<code>
const { Logger, LogLevel } = require("@itwin/core-bentley");
const { SnapshotDb, IModelHost, StandaloneDb, IModelJsFs } = require("@itwin/core-backend");
const { Transformer } = require("@itwin/imodel-transformer");
const path = require("node:path");

async function main() {
  IModelHost.startup();

  Logger.initializeToConsole();
  Logger.setLevelDefault(LogLevel.Trace);
  Logger.setLevel("imodel-transformer", LogLevel.Trace);

  /** @type{IModelDb} */
  let sourceDb;
  /** @type{IModelDb} */
  let sourceDb2;
  /** @type{IModelDb} */
  let targetDb;

  const sourceFile = path.join(__dirname, "./aa.bim")
  const sourceFile2 =  path.join(__dirname, "./bb.bim")
  const targetFile = path.join(__dirname, "./c.bim")

  sourceDb = SnapshotDb.openFile(sourceFile);
  sourceDb2 = SnapshotDb.openFile(sourceFile2);

  if (IModelJsFs.existsSync(targetFile)) {
    IModelJsFs.removeSync(targetFile);
  }

  // use StandaloneDb instead of SnapshotDb to enable processChanges testing
  targetDb = StandaloneDb.createEmpty(targetFile, {
    rootSubject: { name: `${sourceDb.rootSubject.name}-Transformed` },
    ecefLocation: sourceDb.ecefLocation,
  });

  /** @type{TransformerOptions} */
  const transformerOptions = {
    simplifyElementGeometry: true,
    noProvenance: true,
  };

  try {
    await Transformer.transformAll(sourceDb, targetDb, transformerOptions);
    await Transformer.transformAll(sourceDb2, targetDb, transformerOptions);
    sourceDb.close();
    targetDb.close();
    return "test";
  } catch(error) {
    console.log(`${error.message}\n${error.stack}`);
  }

  return "OK";
}

void main()
</pre></code>
</details>

**Comment by MichaelBelousov** [comment] 2024-01-02 16:16
this occurs because your input files have the same version of a dynamic schema (`RevitDynamic`), but `bb.bim` contains classes in that dynamic schema which `aa.bim` does not. I will investigate a fix.

**Comment by wwr1982** [comment] 2024-01-03 02:21
Thank you.

**Comment by MichaelBelousov** [comment] 2024-03-04 12:20
In order to merge iModels with dynamic schemas using the transformer, you must manually merge the dynamic schemas, import the new merged one (it can be an update of one of the two), and remap all elements from the other schema into it.

We are working on additional automation of this process.

**Closed by MichaelBelousov** 2024-03-04 12:20 UTC
