### ISSUE TITLE
MapLayersWidget - sections of background map are not visible around the imodel

### ISSUE THREAD

**Issue by Jake-Screen** [iTwin/itwinjs-core#6595] opened 2024-04-08 18:54 UTC
We are utilizing the MapLayersWidget to provide a background map in our studio application. When adding this to application we use a classId of "UnifiedSelectionViewportControl2D". 

Upon loading an iModel from iModel hub, the map appears blank around the area where our model is centered. Upon zooming out, some parts of the map appear, with clipping appearing in different sections of the map. When zoomed far enough out, we can see a circle of area that is not covered in map.

**Expected behavior**
For the map to be visible in the area of our iModel.

**Screenshots**
![map error booster](https://github.com/iTwin/itwinjs-core/assets/108944699/e064abaf-273b-47cc-99a2-9f122810d175)
![map error booster 2](https://github.com/iTwin/itwinjs-core/assets/108944699/404a860b-c455-4931-a2b9-93ab4f5c7cd5)

- OS: Windows
- Browser : Chrome
- iTwin.js Version: 4.4.0-dev.10

**Comment by Jake-Screen** [comment] 2024-04-08 18:55
@ashar-bentley @FelixGirard

**Comment by pmconne** [comment] 2024-04-08 19:03
Can you please add to your description steps required for somebody else to reproduce the problem?

**Comment by ashar-bentley** [comment] 2024-07-18 21:23
The issue happens when the setAllow3dManipulations is set to false

Steps:

1. Open the heatmap sample that has the following view setting set to false:

line 21:  `viewState.setAllow3dManipulations(false);`

https://www.itwinjs.org/sandboxes/iTwinPlatform/Heatmap%20Decorator

2. Zoom out until you start seeing the background map getting clipped:

![image](https://github.com/user-attachments/assets/e7f84305-ecee-4291-be12-7d96fdc94b65)


Now open my fork of the same sample with line 21 modified to set the value to true:

line 21:  `viewState.setAllow3dManipulations(true);`

https://www.itwinjs.org/sandboxes/AsharGhani/HeatMapDecoratorWith3D-On

The issue is no longer reproducible:
![image](https://github.com/user-attachments/assets/a94b52d0-4e1e-4ab4-9784-a6bf092e6eeb)

**Comment by ashar-bentley** [comment] 2024-07-18 21:25
For some iModels we are seeing a more exacerbated version of this problem, where the problem occurs when fully zoomed in.

**Comment by pmconne** [comment] 2024-07-18 21:55
@markschlosseratbentley @danieliborra

**Comment by danieliborra** [comment] 2024-08-07 09:14
We'll take a look at it in our next sprint

**Comment by MarcNeely** [comment] 2024-10-10 14:36
I don't think there is any masking involved.  This is just a side effect of turning off 3d manipulations.  The only thing you can do there is zoom and the zoom for this mode doesn't take the background map into account, so it is getting clipped by the far frustum plane.

**Comment by MarcNeely** [comment] 2024-10-15 13:34
I believe that I have a fix for this.  The basic problem is that the ellipsoid of the earth is not taken into account when zooming in this mode of a 3d file with 3d manipulations and the camera turned off.

**Comment by MarcNeely** [comment] 2024-10-17 17:37
A PR for a fix for this has been created here: [#7275](https://github.com/iTwin/itwinjs-core/pull/7275)

**Closed** 2024-11-06 16:04 UTC
Labels: bug
