### ISSUE TITLE
Expand editing API for editing base class for additional types.

### ISSUE THREAD

**Issue by christophermlawson** [iTwin/itwinjs-core#5903] opened 2023-08-23 11:40 UTC
ECClass types - Mixin, RelationshipClass, StructClass, CustomAttributeClass should also have the ability to edit the base class.

**Comment by StefanApfel-Bentley** [comment] 2024-04-17 09:02
Partial duplicate of #6582

**Closed** 2024-05-06 09:01 UTC
Labels: ecschema
