### ISSUE TITLE
Access Token Returns "Project Not Found"

### ISSUE THREAD

**Issue by rayking99** [iTwin/itwinjs-core#5592] opened 2023-06-05 05:27 UTC
### Discussed in https://github.com/iTwin/itwinjs-core/discussions/5586

<div type='discussions-op-text'>

<sup>Originally posted by **rayking99** June  2, 2023</sup>
Hi I have a service account - I can generate an access token and my scope is set to allow read of: 

clashdetection:read changedelements:modify changedelements:read clashdetection:modify insights:modify insights:read realitydataanalysis:modify realitydataanalysis:read users:read projects:modify itwins:modify issues:read validation:modify designelementclassification:read forms:modify designelementclassification:modify projects:read validation:read forms:read issues:modify itwins:read

However, once I generate a token using my key I can't utilise it to get projects or issues. The API returns a status of 201

If I generate the key through the 'Try It Out' function on the website it works no problem - I can call the API etc. I put the API generated token in the same place as the 'Try It Out' token and it returns a 200 OK but it is different - for example if I send the request to https://api.bentley.com/itwins/?subClass=Project with the 'Try It Out' token I get my projects, but with the Api generated token it get: 

```
{
    "iTwins": [],
    "_links": {
        "self": {
            "href": "https://api.bentley.com/itwins/?$skip=0&$top=100&subClass=Project"
        }
    }
}
```

It seems like it doesn't link my App to my Account..
</div>

**Comment by aruniverse** [comment] 2023-06-23 03:58
Closing issue as duplicate of https://github.com/iTwin/itwinjs-core/discussions/5586 and has been answered there

**Closed by aruniverse** 2023-06-23 03:58 UTC
