### ISSUE TITLE
Shader fails to initialize uniform variable on linux

### ISSUE THREAD

**Issue by tangytang** [iTwin/itwinjs-core#3737] opened 2022-05-26 09:00 UTC
## Description of Problem
Unable to get Viewer App started due to error in the console:
![Screenshot from 2022-05-26 16-59-18](https://user-images.githubusercontent.com/19624580/170455508-982a1d67-a348-4b07-8f7b-6e0cdb74c4d6.png)

### Error Code

​ Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of HeaderRow which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:89125)
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:83671)
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:76743)
    at div
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:57330)
    at ElementResizeObserver (http://localhost:3000/static/js/vendors~main.chunk.js:352917:34)
    at div
    at Table (http://localhost:3000/static/js/vendors~main.chunk.js:95475:9)
    at div
    at div
    at ElementList (http://localhost:3000/static/js/vendors~main.chunk.js:422371:24)
    at div
    at div
    at div
    at MultiElementPropertyGrid (http://localhost:3000/static/js/vendors~main.chunk.js:422657:114)
    at div
    at ScrollableWidgetContent (http://localhost:3000/static/js/vendors~main.chunk.js:23773:72)
    at WidgetContent (http://localhost:3000/static/js/vendors~main.chunk.js:69546:20)
    at WidgetContentRenderer (http://localhost:3000/static/js/vendors~main.chunk.js:24132:82)
    at WidgetContentRenderers (http://localhost:3000/static/js/vendors~main.chunk.js:24119:75)
    at div
    at WidgetPanelsComponent (http://localhost:3000/static/js/vendors~main.chunk.js:23558:69)
    at WidgetPanels (http://localhost:3000/static/js/vendors~main.chunk.js:23552:109)
    at WidgetInternals (http://localhost:3000/static/js/vendors~main.chunk.js:69678:133)
    at WidgetPanelsFrontstageComponent
    at WidgetContentManager (http://localhost:3000/static/js/vendors~main.chunk.js:24054:87)
    at CursorTypeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:11285:72)
    at DraggedResizeHandleProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10865:19)
    at DraggedPanelSideProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10861:27)
    at DraggedWidgetIdProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10857:21)
    at DragProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10832:69)
    at NineZoneProvider (http://localhost:3000/static/js/vendors~main.chunk.js:11205:106)
    at NineZone (http://localhost:3000/static/js/vendors~main.chunk.js:11192:13)
    at div
    at ActiveFrontstageDefProvider (http://localhost:3000/static/js/vendors~main.chunk.js:69816:40)
    at WidgetPanelsFrontstage (http://localhost:3000/static/js/vendors~main.chunk.js:69798:112)
    at main
    at ConfigurableUiContent (http://localhost:3000/static/js/vendors~main.chunk.js:39810:108)
    at FrameworkVersion (http://localhost:3000/static/js/vendors~main.chunk.js:48691:86)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:393848:23)
    at div
    at ThemeManagerComponent (http://localhost:3000/static/js/vendors~main.chunk.js:64240:9)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:552838:75)
    at IModelViewer (http://localhost:3000/static/js/vendors~main.chunk.js:428932:25)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:552543:20)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:428716:69
    at IModelLoader (http://localhost:3000/static/js/vendors~main.chunk.js:428809:15)
    at ErrorBoundary (http://localhost:3000/static/js/vendors~main.chunk.js:354037:9)
    at BaseViewer (http://localhost:3000/static/js/vendors~main.chunk.js:428155:23)
    at Viewer (http://localhost:3000/static/js/vendors~main.chunk.js:431180:80)
    at div
    at App (http://localhost:3000/static/js/main.chunk.js:182:89)

**Comment by pmconne** [comment] 2022-06-03 12:36
I am able to reproduce this on my Ubuntu box with GPU enabled. The core-frontend shader compilation tests use software rendering, which does not produce this error.

**Comment by pmconne** [comment] 2022-06-03 13:20
Have you considered replacing this:
```
export interface SchemaItemEditResults {
  itemKey?: SchemaItemKey;
  errorMessage?: string;
}
```

With this:
```
export interface SchemaItemEditSuccess {
  itemKey: SchemaItemKey;
  errorMessage?: never;
}

export interface SchemaItemEditError {
  errorMessage: string;
  itemKey?: never;
}

export type SchemaItemEditResults = SchemaItemEditSuccess | SchemaItemEditError;
```

To accurately reflect that the result is exactly one of an item key or an error message, never both nor neither?
This also makes calling code much simpler because the compiler knows that `result.errorMessage` will be `undefined ` IFF `result.itemKey` is `undefined`.

**Comment by pmconne** [comment] 2022-06-03 13:59
Investigation results: the problematic shader's description is "Surface: Opaque-Instanced-Pick". The vertex shader uses u_patternFeatureId to compute g_featureIndex but never forwards the result to the fragment shader, so that all gets optimized away. The fragment shader outputs zero for FragColor1 and FragColor2, instead of outputting the pick data.
The reason that element locate works for instanced surfaces anyway is that we force edge testing while reading pixels, and the "Surface: Opaque-Instanced-EdgeTestNeeded-Pick" shader does correctly output the pick data.

**Comment by pmconne** [comment] 2022-06-06 15:03
This was broken [3 years ago](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodeljs/pullrequest/27164). It appears that (in some/most cases?), the combination of FeatureMode.Pick and IsEdgeTestNeeded.No should be identical to FeatureMode.None - it does nothing with the features. I think possibly this is not true for classifiers?

**Comment by DStradley** [comment] 2022-06-09 23:58
> This appears to have been introduced [3 years ago](https://dev.azure.com/bentleycs/iModelTechnologies/_git/imodeljs/pullrequest/27164). That PR made it so that for the combination of FeatureMode.Pick and IsEdgeTestNeeded.No (excluding classifiers), the shader computes the feature index but does nothing with it. Presumably we were relying on the compiler to optimize out those unnecessary computations, but the introduction of u_patternFeatureId appears to show that only Linux fully optimizes them, including removal of the uniform. Ideally we would not include those computations in the first place.

@pmconne @markschlosseratbentley - I looked at the output glsl, the hlsl, and the compiled assembly for Angle for this case and it is fully optimized.  The way Angle and D3D work, it does leave the u_patternFeatureId in the uniform table, but marks it as unused (which is why we don't get a uniform error).  All references, calculations, texture lookups for calculations, etc. have been removed.  I suppose there is the very small CPU overhead of writing the value to this unused location, and ideally we should not generate unused code in glsl (for confusion if nothing else), but with https://github.com/iTwin/itwinjs-core/pull/3754 done, to me fixing this becomes a low priority.

**Comment by markschlosseratbentley** [comment] 2022-06-10 11:44
Closing this because #3754 is merged and fixed the issue. Related issue #3740 has been also closed. I have created #3773 to track any remaining work based on the comments from @DStradley above.

**Closed by markschlosseratbentley** 2022-06-10 11:44 UTC
Labels: bug, display

**Comment by achrysaetos** [comment] 2022-06-27 20:03
We also fixed the findDOMNode warning in the console with https://github.com/iTwin/viewer-components-react/pull/283.
