### ISSUE TITLE
Flaky webpack tests

### ISSUE THREAD

**Issue by pmconne** [iTwin/itwinjs-core#4354] opened 2022-09-25 15:47 UTC
**Describe the bug**
RequireMagicComments plugin tests frequently fail, on Windows only, during CI.

**To Reproduce**
Submit a PR.
Await test failures.

**Expected behavior**
Tests pass consistently.

**Screenshots**

**Desktop (please complete the applicable information):**

- OS: [e.g. iOS] Windows CI
- Browser [e.g. chrome, safari] n/a
- Version [e.g. 22] n/a
- iTwin.js Version [e.g. 2.5.3] master

**Additional context**
Allegedly, regenerating the snap files on a Windows machine "fixes" it. But it keeps recurring.
Attempting to do so on a non-Windows machine has no effect, and the tests continue to pass in the absence of the snap files.

```
2022-09-25T14:48:22.4218595Z [0m  1) RequireMagicCommentsPlugin
2022-09-25T14:48:22.4219136Z        should work with copyfile comments and addCopyFileSuffix handler:
2022-09-25T14:48:22.4219460Z 
2022-09-25T14:48:22.4220099Z       [31mAssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with copyfile comments and addCopyFileSuffix handler 1[0m
2022-09-25T14:48:22.4220873Z       [32m+ expected[0m [31m- actual[0m
2022-09-25T14:48:22.4221157Z 
2022-09-25T14:48:22.4221515Z        exports.id = 179;
2022-09-25T14:48:22.4221912Z        exports.ids = [179];
2022-09-25T14:48:22.4222318Z        exports.modules = {
2022-09-25T14:48:22.4222701Z        
2022-09-25T14:48:22.4223077Z       [31m-/***/ 993:[0m
2022-09-25T14:48:22.4223480Z       [32m+/***/ 861:[0m
2022-09-25T14:48:22.4223999Z        /***/ ((module, __unused_webpack_exports, __webpack_require__) => {
2022-09-25T14:48:22.4224508Z        
2022-09-25T14:48:22.4225081Z        module.exports = (__webpack_require__(17).resolve)(__dirname, __webpack_require__.p + "static/bar.d9b9bf.txt");
2022-09-25T14:48:22.4225753Z        
2022-09-25T14:48:22.4226106Z --
2022-09-25T14:48:22.4226469Z        
2022-09-25T14:48:22.4226826Z        /***/ 67:
2022-09-25T14:48:22.4227408Z        /***/ ((__unused_webpack_module, __unused_webpack_exports, __webpack_require__) => {
2022-09-25T14:48:22.4227997Z        
2022-09-25T14:48:22.4228480Z       [31m-__webpack_require__(/*webpack: copyfile*/993);[0m
2022-09-25T14:48:22.4229120Z       [32m+__webpack_require__(/*webpack: copyfile*/861);[0m
2022-09-25T14:48:22.4229609Z        
2022-09-25T14:48:22.4229962Z        /***/ }),
2022-09-25T14:48:22.4230317Z        
2022-09-25T14:48:22.4230668Z        /***/ 17:
2022-09-25T14:48:22.4231028Z       [0m[90m
2022-09-25T14:48:22.4231591Z       at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:96:114)
2022-09-25T14:48:22.4232156Z [0m
2022-09-25T14:48:22.4232529Z [0m  2) RequireMagicCommentsPlugin
2022-09-25T14:48:22.4233055Z        should work with copyfile comments, addCopyFileSuffix, and resolve converted:
2022-09-25T14:48:22.4233412Z 
2022-09-25T14:48:22.4234041Z       [31mAssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with copyfile comments, addCopyFileSuffix, and resolve converted 1[0m
2022-09-25T14:48:22.4235287Z       [32m+ expected[0m [31m- actual[0m
2022-09-25T14:48:22.4235561Z 
2022-09-25T14:48:22.4235909Z        exports.id = 179;
2022-09-25T14:48:22.4236317Z        exports.ids = [179];
2022-09-25T14:48:22.4236736Z        exports.modules = {
2022-09-25T14:48:22.4237113Z        
2022-09-25T14:48:22.4237492Z       [31m-/***/ 993:[0m
2022-09-25T14:48:22.4237886Z       [32m+/***/ 861:[0m
2022-09-25T14:48:22.4238405Z        /***/ ((module, __unused_webpack_exports, __webpack_require__) => {
2022-09-25T14:48:22.4238903Z        
2022-09-25T14:48:22.4239489Z        module.exports = (__webpack_require__(17).resolve)(__dirname, __webpack_require__.p + "static/bar.d9b9bf.txt");
2022-09-25T14:48:22.4240107Z        
2022-09-25T14:48:22.4240452Z --
2022-09-25T14:48:22.4240776Z        
2022-09-25T14:48:22.4241131Z        /***/ 67:
2022-09-25T14:48:22.4241676Z        /***/ ((__unused_webpack_module, __unused_webpack_exports, __webpack_require__) => {
2022-09-25T14:48:22.4242221Z        
2022-09-25T14:48:22.4242680Z       [31m-__webpack_require__(/*webpack: copyfile*/993);[0m
2022-09-25T14:48:22.4243273Z       [32m+__webpack_require__(/*webpack: copyfile*/861);[0m
2022-09-25T14:48:22.4243753Z        
2022-09-25T14:48:22.4244114Z        /***/ }),
2022-09-25T14:48:22.4244503Z        
2022-09-25T14:48:22.4244860Z        /***/ 17:
2022-09-25T14:48:22.4245210Z       [0m[90m
2022-09-25T14:48:22.4245752Z       at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:109:114)
2022-09-25T14:48:22.4246824Z [0m
2022-09-25T14:48:22.4247243Z [0m  3) RequireMagicCommentsPlugin
2022-09-25T14:48:22.4247827Z        should work with copyfile comments, addCopyFileSuffix, and resolve not converted:
2022-09-25T14:48:22.4248203Z 
2022-09-25T14:48:22.4248901Z       [31mAssertionError: expected value to match snapshot RequireMagicCommentsPlugin should work with copyfile comments, addCopyFileSuffix, and resolve not converted 1[0m
2022-09-25T14:48:22.4249746Z       [32m+ expected[0m [31m- actual[0m
2022-09-25T14:48:22.4250029Z 
2022-09-25T14:48:22.4250392Z        exports.id = 179;
2022-09-25T14:48:22.4250813Z        exports.ids = [179];
2022-09-25T14:48:22.4251236Z        exports.modules = {
2022-09-25T14:48:22.4251615Z        
2022-09-25T14:48:22.4251960Z       [31m-/***/ 993:[0m
2022-09-25T14:48:22.4252375Z       [32m+/***/ 861:[0m
2022-09-25T14:48:22.4252877Z        /***/ ((module, __unused_webpack_exports, __webpack_require__) => {
2022-09-25T14:48:22.4253381Z        
2022-09-25T14:48:22.4253982Z        module.exports = (__webpack_require__(17).resolve)(__dirname, __webpack_require__.p + "static/bar.d9b9bf.txt");
2022-09-25T14:48:22.4254633Z        
2022-09-25T14:48:22.4254959Z --
2022-09-25T14:48:22.4255287Z        
2022-09-25T14:48:22.4255634Z        /***/ 67:
2022-09-25T14:48:22.4256008Z        /***/ (() => {
2022-09-25T14:48:22.4256362Z        
2022-09-25T14:48:22.4256808Z       [31m-/*require.resolve*/(/*webpack: copyfile*/993);[0m
2022-09-25T14:48:22.4257419Z       [32m+/*require.resolve*/(/*webpack: copyfile*/861);[0m
2022-09-25T14:48:22.4257881Z        
2022-09-25T14:48:22.4258234Z        /***/ }),
2022-09-25T14:48:22.4258583Z        
2022-09-25T14:48:22.4258928Z        /***/ 17:
2022-09-25T14:48:22.4259387Z       [0m[90m
2022-09-25T14:48:22.4259924Z       at Context.<anonymous> (lib\test\RequireMagicCommentsPlugin.test.js:121:114)
2022-09-25T14:48:22.4260449Z [0m
2022-09-25T14:48:22.4260628Z 
2022-09-25T14:48:22.4260816Z 
2022-09-25T14:48:22.4261133Z Returned error code: 3
```

**Comment by aruniverse** [comment] 2022-09-25 18:36
Duplicate of https://github.com/iTwin/itwinjs-core/issues/4327

**Closed** 2022-09-25 18:37 UTC
Labels: flaky-test
