### ISSUE TITLE
Atmospheric Scattering does not always behave as expected

### ISSUE THREAD

**Issue by RaphaelMelancon** [iTwin/itwinjs-core#4475] opened 2022-10-11 19:41 UTC
Sometimes, when the atmospheric scattering effect is enabled, it does not apply properly.

The effect should look as if the further away from the earth a pixel is, the less it should be affected by atmospheric scattering. Like so: 
![atmospheric_scattering_sky](https://user-images.githubusercontent.com/98826280/195183344-f66ee0c4-644e-47a4-8884-4da24884be94.jpg)

However, sometimes viewing the earth approximately the atmosphere's outer limit, it appears like there is a second atmosphere coming from the opposite direction:
![atmosphere_issue](https://user-images.githubusercontent.com/98826280/195182886-a29756a0-5eee-4a97-a133-310751954de8.png)

**Comment by markschlosseratbentley** [comment] 2022-10-11 20:17
@RaphaelMelancon Is this a duplicate of https://github.com/iTwin/itwinjs-backlog/issues/448 ?

**Comment by RaphaelMelancon** [comment] 2022-10-11 20:28
> @RaphaelMelancon Is this a duplicate of [iTwin/itwinjs-backlog#448](https://github.com/iTwin/itwinjs-backlog/issues/448) ?

Yes, it is, my bad!

**Comment by markschlosseratbentley** [comment] 2022-10-11 20:32
> > @RaphaelMelancon Is this a duplicate of [iTwin/itwinjs-backlog#448](https://github.com/iTwin/itwinjs-backlog/issues/448) ?
> 
> Yes, it is, my bad!

@RaphaelMelancon 
All good, thanks!

**Comment by evelynpreslar-bentley** [comment] 2022-12-06 20:16
Closing as duplicate

**Closed by evelynpreslar-bentley** 2022-12-06 20:16 UTC
Labels: bug, display
